### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by mike-egg123** [MrMino/dockernel#27]
I have a problem that:
```
Traceback (most recent call last):
  File "/data/yyf-qrn/conda/envs/qrn/bin/dockernel", line 8, in <module>
    sys.exit(main())
  File "/data/yyf-qrn/conda/envs/qrn/lib/python3.8/site-packages/dockernel/__main__.py", line 6, in main
    return run(sys.argv)
  File "/data/yyf-qrn/conda/envs/qrn/lib/python3.8/site-packages/dockernel/app.py", line 7, in run
    return run_subcommand(parsed_args)
  File "/data/yyf-qrn/conda/envs/qrn/lib/python3.8/site-packages/dockernel/cli/main.py", line 23, in run_subcommand
    return parsed_args.func(parsed_args)
  File "/data/yyf-qrn/conda/envs/qrn/lib/python3.8/site-packages/dockernel/cli/install.py", line 77, in install
    install_kernelspec(location, kernelspec)
  File "/data/yyf-qrn/conda/envs/qrn/lib/python3.8/site-packages/dockernel/kernelspec.py", line 163, in install_kernelspec
    raise ValueError(f"kernelspec already exists: {kernelspec_dir}.")
ValueError: kernelspec already exists: /home/jupyter-yyf-qrn/.local/share/jupyter/kernels.
```
Could you tell me how to solve it?

**Comment by MrMino** [comment]
Please show the command that you were using. I think you somehow omitted the location argument, but I'm not sure how.
